import {loanType, occupationType, documentImageType} from './enums';

export const loan_document_requirements = [
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      'Land ownership proof (Patta, RTC, Khasra-Khatauni)',
      'Agricultural income proof (Crop sales receipts)',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Loan Sanction Letter',
      'EMI Track Record',
      'Loan Closure No Objection Certificate (NOC)',
      'RC Copy',
      'Updated Insurance Details',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      "Last 3 months' salary slips",
      "Last 6 months' bank statements showing salary credits",
      'Form 16 / Income Tax Returns (ITR)',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Loan Sanction Letter',
      'EMI Track Record',
      'Loan Closure No Objection Certificate (NOC)',
      'RC Copy',
      'Updated Insurance Details',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      "Last 2 years' ITR",
      'Profit and Loss statement for the last 2 years',
      'Balance Sheet for the last 2 years',
      'Business Registration Certificate or Trade License',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Loan Sanction Letter',
      'EMI Track Record',
      'Loan Closure No Objection Certificate (NOC)',
      'RC Copy',
      'Updated Insurance Details',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      'All self-employed documents',
      'Professional qualification certificates (e.g., MBBS, LLB)',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.externalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Loan Sanction Letter',
      'EMI Track Record',
      'Loan Closure No Objection Certificate (NOC)',
      'RC Copy',
      'Updated Insurance Details',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      'Land ownership proof (Patta, RTC, Khasra-Khatauni)',
      'Agricultural income proof (Crop sales receipts)',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Loan Sanction Letter',
      'EMI Track Record',
      'Updated Insurance Details',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: ['Passport', 'Driving License', 'Voter ID Card (EPIC)'],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      "Last 3 months' salary slips",
      "Last 6 months' bank statements showing salary credits",
      'Form 16 / Income Tax Returns (ITR)',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SALARIED,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Loan Sanction Letter',
      'EMI Track Record',
      'Updated Insurance Details',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      "Last 2 years' ITR",
      'Profit and Loss statement for the last 2 years',
      'Balance Sheet for the last 2 years',
      'Business Registration Certificate or Trade License',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Loan Sanction Letter',
      'EMI Track Record',
      'Updated Insurance Details',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      'All self-employed documents',
      'Professional qualification certificates (e.g., MBBS, LLB)',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.internalBT,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Loan Sanction Letter',
      'EMI Track Record',
      'Updated Insurance Details',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      'Land ownership proof (Patta, RTC, Khasra-Khatauni)',
      'Agricultural income proof (Crop sales receipts)',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Vehicle RC',
      'Current Insurance Copy',
      'Loan Closure Statement or No Objection Certificate (NOC)',
      'Outstanding Loan Balance Certificate',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      "Last 3 months' salary slips",
      "Last 6 months' bank statements showing salary credits",
      'Form 16 / Income Tax Returns (ITR)',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SALARIED,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Vehicle RC',
      'Current Insurance Copy',
      'Loan Closure Statement or No Objection Certificate (NOC)',
      'Outstanding Loan Balance Certificate',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      "Last 2 years' ITR",
      'Profit and Loss statement for the last 2 years',
      'Balance Sheet for the last 2 years',
      'Business Registration Certificate or Trade License',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Vehicle RC',
      'Current Insurance Copy',
      'Loan Closure Statement or No Objection Certificate (NOC)',
      'Outstanding Loan Balance Certificate',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      'All self-employed documents',
      'Professional qualification certificates (e.g., MBBS, LLB)',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.refinance,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Existing Vehicle RC',
      'Current Insurance Copy',
      'Loan Closure Statement or No Objection Certificate (NOC)',
      'Statement of account(SOA)',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      'Land ownership proof (Patta, RTC, Khasra-Khatauni)',
      'Agricultural income proof (Crop sales receipts)',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Electricity Bill (not older than 3 months)',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      "Last 3 months' salary slips",
      "Last 6 months' bank statements showing salary credits",
      'Form 16 / Income Tax Returns (ITR)',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      "Last 2 years' ITR",
      'Profit and Loss statement for the last 2 years',
      'Balance Sheet for the last 2 years',
      'Business Registration Certificate or Trade License',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      'All self-employed documents',
      'Professional qualification certificates (e.g., MBBS, LLB)',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.purchase,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      'Land ownership proof (Patta, RTC, Khasra-Khatauni)',
      'Agricultural income proof (Crop sales receipts)',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.AGRICULTURE,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Current Loan Statement',
      'Sanction Letter of Existing Loan',
      'Outstanding Loan Balance Certificate',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      "Last 3 months' salary slips",
      "Last 6 months' bank statements showing salary credits",
      'Form 16 / Income Tax Returns (ITR)',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SALARIED,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SALARIED,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Current Loan Statement',
      'Sanction Letter of Existing Loan',
      'Outstanding Loan Balance Certificate',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      "Last 2 years' ITR",
      'Profit and Loss statement for the last 2 years',
      'Balance Sheet for the last 2 years',
      'Business Registration Certificate or Trade License',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Current Loan Statement',
      'Sanction Letter of Existing Loan',
      'Outstanding Loan Balance Certificate',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.ADDRESS_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
      'Electricity Bill (not older than 3 months)',
      'Water Bill (not older than 3 months)',
      'Gas Bill (not older than 3 months)',
      'Telephone Bill (Landline/Postpaid, not older than 3 months)',
      'Rent Agreement (Registered)',
      'Lease Agreement',
      'Bank Passbook/Statement (updated within the last 6 months)',
      'Registered Sale Deed',
      'Property Tax Receipt',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.BANKING_PROOF,
    acceptedDocuments: [
      "Last 6 months' bank statements",
      'Bank Passbook with updated transactions',
      'Cancelled Cheque',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.ID_PROOF,
    acceptedDocuments: [
      'Aadhaar Card',
      'Passport',
      'Driving License',
      'Voter ID Card (EPIC)',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.INCOME_PROOF,
    acceptedDocuments: [
      'All self-employed documents',
      'Professional qualification certificates (e.g., MBBS, LLB)',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.OTHER_DOCUMENTS,
    acceptedDocuments: [
      'Application Form (Signed by Applicant and Co-Applicant, if applicable)',
      'Passport-Sized Photographs',
      'Co-Applicant Documents (if applicable): Same set of identity, address, and income proofs',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: documentImageType.PERMANENT_ADDRESS,
    acceptedDocuments: [
      'Aadhaar Card',
      'Registered Sale Deed',
      'Property Tax Receipt',
      'Letter from Gram Panchayat (Rural Areas)',
      'Bank Statement with Permanent Address',
    ],
  },
  {
    loadProduct: loanType.topUp,
    typeOfIndividual: occupationType.SELF_EMPLOYED_PROFESSIONAL,
    documentType: 'documentImageType.SPECIAL_DOCUMENTS',
    acceptedDocuments: [
      'Current Loan Statement',
      'Sanction Letter of Existing Loan',
      'Outstanding Loan Balance Certificate',
    ],
  },
];
