const ScreenNames = {
  // Auth
  Splash: 'SplashScreen',
  Login: 'LoginScreen',
  OTP: 'OTPScreen',

  // Home
  HomeTab: 'HomeTab',
  Home: 'HomeScreen',
  Applications: 'ApplicationsScreen',
  Customer: 'CustomersScreen',
  Vehicles: 'VehiclesScreen',

  // Others
  NotFound: 'NotFoundScreen',
  Notification: 'NotificationScreen',
  SearchView: 'SearchScreen',
  VehicleDetail: 'VehicleDetailScreen',
  VehicleImages: 'VehicleImages',
  VehicleOdometer: 'VehicleOdometer',
  VehiclePricing: 'VehiclePricing',
  CustomerDetail: 'CustomerDetailScreen',
  CustomerPersonalDetails: 'CustomerPersonalDetails',
  LoanDocument: 'LoanDocumentScreen',
  LoanAmount: 'LoanAmountScreen',
  CheckCIBIL: 'CheckCIBILScreen',
  CustomerEnvelope: 'CustomerEnvelopeScreen',
  LenderSelection: 'LenderSelectionScreen',
  LoanOfferDetail: 'LoanOfferDetailScreen',
  AddReference: 'AddReferenceScreen',
  ViewLoanDetail: 'ViewLoanDetailsScreen',
  VehicleHypothecation: 'VehicleHypothecationScreen',
  FinanceDetails: 'FinanceDetailsScreen',
  FinanceDocuments: 'FinanceDocumentsScreen',
  ThankYouView: 'ThankYouScreen',
  TrackApplication: 'TrackApplicationScreen',
  CarFinanceDetails: 'CarFinanceDetailsScreen',
  TopUpFinanceDocuments: 'TopUpFinanceDocumentsScreen',
  LenderDetails: 'LenderDetailsScreen',
  CustomizeLoanOffer: 'CustomizeLoanOfferScreen',
  CustomerInfo: 'CustomerInfoScreen',
  CustomerDocuments: 'CustomerDocumentsScreen',
  CustomerFinancialDocs: 'CustomerFinancialDocsScreen',
  MoreOnFinancial: 'MoreOnFinancialScreen',
  UserProfile: 'ProfileScreen',
  EditProfile: 'EditProfileScreen',
  ManageMember: 'ManageMembersScreen',
  ChangePassword: 'ChangePasswordScreen',
  FAQS: 'FAQScreen',
  ContactSupport: 'ContactSupportScreen',
  Logout: 'logout',
  NewLoanCustomerOtp: 'NewLoanCustomerOtpScreen',
  SelectVehicle: 'SelectVehicleScreen',
  ProformaInvoice: 'ProformaInvoiceScreen',
  SuccessScreen: 'SuccessScreen',
};

export default ScreenNames;
